Send email on completion of daily index if MAIL_INDEX_TODAY_RESULTS_TO is set

diff --git a/bin/index_date b/bin/index_date
--- a/bin/index_date
+++ b/bin/index_date
@@ -62,7 +62,6 @@ fi
 
 log "Targeting $target_url"
 
-
 log "Sleeping for 5s" $logfile
 sleep 5
 
@@ -72,9 +71,11 @@ if [ -f "$delfile" ]; then
   delout=`bundle exec jruby $SCRIPTDIR/delete_ids "$delfile" "$target_url"`
   log "$delout" "$logfile"
 else
-  log  "Could not find delfile '$delfile'" $logfile
+  log "Could not find delfile '$delfile'" $logfile
   log "Assuming no deletes for date $DATE" $logfile
 fi
 
 cd $TDIR
 $SCRIPTDIR/index_file $marcfile $port $logfile
+
+exit $?
diff --git a/bin/index_today b/bin/index_today
--- a/bin/index_today
+++ b/bin/index_today
@@ -26,24 +26,43 @@ fi
 HERE=`dirname $0`
 SCRIPTDIR=`realpath $HERE`
 
-
-port=$1
-
-LOGFILE=$2
+mailto=${MAIL_INDEX_TODAY_RESULTS_TO}
 
 TODAY=`/bin/date +"%Y%m%d"`
 
+port=$1
+[[ -z "$port" ]] && port=8025
 
+LOGFILE=$2
 if [ -z $LOGFILE ]; then
-    LOGFILE=`realpath "$SCRIPTDIR/../logs/daily/daily_${TODAY}.txt"`
+    logfiledir=`realpath "$SCRIPTDIR/../logs/daily/$port"`
+    mkdir -p $logfiledir
+    LOGFILE="$logfiledir/daily_${TODAY}.txt"
 else
     LOGFILE=`realpath "$LOGFILE"`
 fi
 
 
+$SCRIPTDIR/index_date $TODAY $port $LOGFILE
 
-$SCRIPTDIR/index_date $TODAY $port $LOGFILE 
-tail -10 $LOGFILE
-grep ERR $LOGFILE
+traject_exit_value=$?
+hostname=`hostname -s`
+
+tally=`grep finished ${LOGFILE} | tail -1 | cut -f7 -d':' | cut -f1 -d';'`
+
+if grep -q "returning 'false'" $LOGFILE; then
+    subject="FAILURES. ${hostname} catalog, port ${port} did ${tally}"
+    errors=`grep ERROR ${LOGFILE}  | grep "not add"`
+    newlines=$'\n\n'
+    body=$(printf "See ${LOGFILE} for specifics.$newlines${errors}")
+else
+    subject="SUCCESS. ${hostname} catalog, port ${port} did ${tally}"
+fi
+
+
+if [[ ! -z $mailto ]]; then 
+    echo -e "$body" | mail -s "$subject" "$mailto"
+fi
+
 
 
